# Generated by Django 4.0 on 2021-12-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='state_id',
            new_name='state',
        ),
    ]
