# Generated by Django 4.0 on 2021-12-17 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_city_id_event_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='publiished',
            new_name='published',
        ),
    ]
